"""empty message

Revision ID: 4b1880aa9a4d
Revises: 37a12a6d8308
Create Date: 2021-11-05 23:26:31.592560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b1880aa9a4d'
down_revision = '37a12a6d8308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_total')
    # ### end Alembic commands ###
